FROM node:12

WORKDIR /usr/src/app
RUN npm install -g serve

COPY package*.json ./
RUN npm ci --only=production
COPY . .
ENV REACT_APP_COMPANY_NAME=$REACT_APP_COMPANY_NAME
ENV REACT_APP_DAILY_SUBDOMAIN=$REACT_APP_DAILY_SUBDOMAIN
ENV REACT_APP_COMPANY_URL=$REACT_APP_COMPANY_URL
ENV PORT=3000
RUN npm run build
CMD serve -s build
