FROM node:12 as builder

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm ci --only=production
COPY . .
ARG REACT_APP_COMPANY_NAME
ARG REACT_APP_DAILY_SUBDOMAIN
ARG REACT_APP_COMPANY_URL

ENV REACT_APP_COMPANY_NAME=$REACT_APP_COMPANY_NAME
ENV REACT_APP_DAILY_SUBDOMAIN=$PORREACT_APP_DAILY_SUBDOMAIN
ENV REACT_APP_COMPANY_URL=$REACT_APP_COMPANY_URL
RUN npm run build

FROM bitnami/nginx
EXPOSE 8080
COPY --from=builder /usr/src/app/build /app